### ISSUE TITLE
Question - C:\SFFabricBin\vc14_redist.x64.exe -quiet C:\SFFabricBin\vcredist_x64.exe -quiet

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-scripts-and-templates#8]
Hello Team,

do these exe contains runtime of SF ?
are you trying to run these exe during build stage of docker ?

Thanks,
Naresh Khatri

**Comment by roshanroutray** [comment]
These exe are VC++ pre requisites for SF runtime. These will be moved to docker image that we will publish. Tracking issue https://github.com/Azure/service-fabric-scripts-and-templates/issues/13
